# SPDX-FileCopyrightText: Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

c_compiler_version:
  - 9.4

cxx_compiler_version:
  - 9.4

cuda_compiler:
  - nvcc

cuda_compiler_version:
  - 11.4

python:
  - 3.8
  - 3.9

# Setup the dependencies to build with multiple versions of RAPIDS
rapids_version:
  - 21.10 # 22.06 is final release with support for RAPIDS 21.10
  - 22.04 # Keep around compatibility with current version -1
  - 22.06

abseil_cpp:
  - 20211102.0
  - 20211102.0
  - 20210324.2

glog:
  - 0.5
  - 0.5
  - 0.6 # 0.6 is needed for cudf>=22.06

grpc_cpp:
  - 1.43
  - 1.43
  - 1.45 # 1.45 is needed for cudf>=22.06

zip_keys:
  - rapids_version
  - glog
  - grpc_cpp

# The following mimic what is available in the pinning feedstock:
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml
boost:
  - 1.74.0
boost_cpp:
  - 1.74.0
gflags:
  - 2.2
ucx:
  - 1.12


pin_run_as_build:
  boost-cpp:
    max_pin: x.x
