name: mrc-quickstart

channels:
  - conda-forge
  - rapidsai
  - nvidia
  - rapidsai-nightly
  - nvidia/label/dev

dependencies:
  - autoconf>=2.69
  - benchmark=1.6.0
  - ccache
  - cmake=3.22
  - cuda-nvml-dev=11.4
  - cudatoolkit=11.4
  - cython=0.29.24
  - doxygen=1.9.2
  - gcc_linux-64=11.2
  - gmock=1.10
  - graphviz=3.0
  - gtest=1.10
  - gxx_linux-64=11.2
  - libtool
  - ninja=1.10
  - numactl-libs-cos7-x86_64
  - numpy=1.21.2
  - nvcc_linux-64=11.4
  - pkg-config=0.29
  - python=3.8
  - scikit-build>=0.12
  - spdlog=1.8.5
  - mrc=22.11
  - sysroot_linux-64=2.17
  - pip:
    - cython
    - flake8
    - isort
    - numpy==1.21.2
    - pytest
    - pytest-timeout
    - yapf
