name: mrc-quickstart

channels:
  - conda-forge
  - rapidsai
  - nvidia
  - rapidsai-nightly
  - nvidia/label/dev

dependencies:
  - autoconf>=2.69
  - benchmark=1.6.0
  - ccache
  - cmake=3.22
  - cuda-nvml-dev=11.8
  - cudatoolkit=11.8
  - cython=0.29.24
  - doxygen=1.9.2
  - gcc_linux-64=11.2
  - gmock=1.13
  - graphviz=3.0
  - gtest=1.13
  - gxx_linux-64=11.2
  - isort
  - libtool
  - ninja=1.10
  - numactl-libs-cos7-x86_64
  - numpy>=1.21
  - nvcc_linux-64=11.8
  - pkg-config=0.29
  - python=3.10
  - scikit-build>=0.12
  - mrc=24.10
  - sysroot_linux-64=2.17
  - pip:
    - cython
    - flake8
    - numpy==1.21.2
    - pytest
    - pytest-timeout
    - yapf
